name: dart_extensions
description: Set of method-extensions for dart that makes using framework in a much easier and clean way also adds additional functionality.
version: 1.0.5
documentation: https://github.com/droididan/dart_extentions
homepage: https://github.com/droididan/dart_extentions

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  intl: ^0.17.0
  quiver: ^3.0.0
  http: ^0.13.0
  test_api: ^0.3.0
  flutter:
    sdk: flutter

dependency_overrides:
  test_api: ^0.2.19

dev_dependencies:
  test: ^1.16.7
  flutter_test:
    sdk: flutter